//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASIC.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASIC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asic {
            get {
                object obj = ResourceManager.GetObject("asic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ajustes_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-ajustes-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_alerta_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-alerta-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_botón_maximizar_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-botón-maximizar-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_botón_maximizar_32__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-botón-maximizar-32 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cerrar_ventana_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-cerrar-ventana-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cerrar_ventana_32__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-cerrar-ventana-32 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_contraseña_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-contraseña-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_10 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_29 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_32__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-32 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_52 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_editar_521 {
            get {
                object obj = ResourceManager.GetObject("icons8-editar-521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_eliminar_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-eliminar-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_eliminar_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-eliminar-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_google_web_search_52 {
            get {
                object obj = ResourceManager.GetObject("icons8-google-web-search-52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_google_web_search_52__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-google-web-search-52 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_google_web_search_52__2_ {
            get {
                object obj = ResourceManager.GetObject("icons8-google-web-search-52 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_google_web_search_521 {
            get {
                object obj = ResourceManager.GetObject("icons8-google-web-search-521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_hand_with_a_pill_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-hand-with-a-pill-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_hoja_de_cálculo_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-hoja-de-cálculo-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-home-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_minimizar_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-minimizar-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_minimizar_la_ventana_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-minimizar-la-ventana-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_people_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-people-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_people_50__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-people-50 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_people_501 {
            get {
                object obj = ResourceManager.GetObject("icons8-people-501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_pills_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-pills-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restaurar_abajo_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-restaurar-abajo-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restore_down_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-restore-down-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2024_11_03_a_las_00_58_43_3208a3dd {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2024-11-03 a las 00.58.43_3208a3dd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_usuario {
            get {
                object obj = ResourceManager.GetObject("img-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_usuario1 {
            get {
                object obj = ResourceManager.GetObject("img-usuario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxi {
            get {
                object obj = ResourceManager.GetObject("maxi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;web&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.borde {
        ///            border-collapse: collapse;
        ///            border-spacing: 0; /* Elimina espacio entre celdas */
        ///        }
        ///
        ///        table.border th, table.border td {
        ///            padding: 5px; /* Ajustado el padding a 5px para eliminar espacio entre celdas */
        ///            border: 1px solid black;
        ///        }
        ///
        ///        button {
        ///            background-color: #008CBA;
        ///            color: white;
        ///            padding: 10px [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla {
            get {
                return ResourceManager.GetString("plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;web&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.borde {
        ///            border-collapse: collapse;
        ///            border-spacing: 0; /* Elimina espacio entre celdas */
        ///        }
        ///
        ///        table.border th, table.border td {
        ///            padding: 5px; /* Ajustado el padding a 5px para eliminar espacio entre celdas */
        ///            border: 1px solid black;
        ///        }
        ///
        ///        button {
        ///            background-color: #008CBA;
        ///            color: white;
        ///            padding: 10px [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla_salidas {
            get {
                return ResourceManager.GetString("plantilla_salidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;web&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.borde {
        ///            border-collapse: collapse;
        ///            border-spacing: 0; /* Elimina espacio entre celdas */
        ///        }
        ///
        ///        table.border th, table.border td {
        ///            padding: 5px; /* Ajustado el padding a 5px para eliminar espacio entre celdas */
        ///            border: 1px solid black;
        ///        }
        ///
        ///        button {
        ///            background-color: #008CBA;
        ///            color: white;
        ///            padding: 10px [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reportes_medicamentos {
            get {
                return ResourceManager.GetString("reportes_medicamentos", resourceCulture);
            }
        }
    }
}
